[build]
# Use native CPU features for maximum performance
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static",
]

# Link-time optimization for release builds
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native",
    "-C", "target-feature=+avx2,+fma,+bmi2,+popcnt",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+avx2,+fma,+bmi2,+popcnt",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+neon,+crypto,+crc",
]

# Profile-guided optimization support
[env]
CARGO_PROFILE_RELEASE_LTO = "fat"
CARGO_PROFILE_RELEASE_CODEGEN_UNITS = "1"
CARGO_PROFILE_RELEASE_PANIC = "abort"