# Planet Scale DNS Server Configuration Example

[server]
bind_address = "0.0.0.0"
port = 53
max_connections = 10000

[storage]
data_dir = "./data"
cache_size_mb = 1024

[cluster]
enabled = false
# node_id = 12345

[api]
enabled = true
bind_address = "127.0.0.1"
port = 8080